[package]
name = "funny_endponts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
serde_json = "1.0.107"
serde = "1.0.188"
rocket = { version = "0.5.0-rc.3", features = [ "json" ] }
tokio-postgres = "0.7.10"
uuid = "1.4.1"

